site_name: Jiki
theme:
  name: material
plugins:
  - search
  - mkdocstrings:            # ← walks your package & renders docs
      handlers:
        python:
          options:
            merge_init_into_package: true
nav:
  - Home: index.md
  - Concepts:
      - Architecture: https://modelcontextprotocol.io/docs/concepts/architecture
      - Tools: https://gofastmcp.com/servers/tools
      - Resources: https://gofastmcp.com/servers/resources
      - Prompts: https://gofastmcp.com/servers/prompts
      - Context: https://gofastmcp.com/servers/context
      - Transports: https://modelcontextprotocol.io/docs/concepts/transports
  - Reference:
      - API: reference.md    # will be filled by mkdocstrings 